### ISSUE TITLE
Cannot install config if candidate change username

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#471]
### Description of Issue/Question
When the candidate configuration change an username, the configuration replace ask for a confirmation:
```
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]
```
load_replace_candidate hangs and fails to complete.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [x] Yes
- [ ] No

### napalm-ios version
(Paste verbatim output from `pip freeze | grep napalm-ios` between quotes below)

```
-e git+https://github.com/napalm-automation/napalm-ios@8cf5d607a5b8e285d505c6827f828f659ca3d781#egg=napalm_ios
```

### IOS version
(Paste verbatim output from `show version` between quotes below)

```
Version 03.06.06E
```

### Steps to Reproduce the Issue
load_replace_candidate a configuration that has different username than those defined in the running

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
cannot install config: Search pattern never detected in send_command_expect: [>##]\\s*$
```

---

Issue moved from https://github.com/napalm-automation/napalm-ios/issues/215

**Comment by bewing** [comment]
Perhaps a similar approach to the `napalm.eos.eos.EOSDriver_load_config()` shims I added for comments and HEREDOCs to shim in a newline or two?

**Comment by ktbyers** [comment]
I am not seeing this issue on Cisco IOS:

```
show archive config differences flash:/candidate_config.txt
!Contextual Config Diffs:
-username test1 secret 5 $1$CQCe$xooaB1jFAZQAWt/3eXub41

pynet-rtr1#configure replace flash:candidate_config.txt force revert trigger error 
Total number of passes: 1
Rollback Done

```

**Comment by ktbyers** [comment]
@targuan Can you still reproduce this? I was unable to reproduce it.

Assuming you can, can you show the config diff between the old and the new config. Also can you show the full napalm stack trace, and the OS version you are currently using.

Thanks.

**Comment by targuan** [comment]
@ktbyers I can still reproduce this in 03.06.06E (IOS-XE train, I'm hitting this on a C3650).

Note that I only have one user on this device and I'm trying to change its name.

```switch#show run | i username
username admin privilege 15 secret 5 some_secret_crypted_password
switch#show archive config differences flash:/candidate_config.txt
!Contextual Config Diffs:
+username admin2 privilege 15 secret 5 same_secret_crypted_password
-username admin privilege 15 secret 5 same_secret_crypted_password

switch#configure replace flash:candidate_config.txt force revert trigger error 
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]```

**Comment by ktbyers** [comment]
Okay, let me see if I can reproduce that behavior.

**Comment by PhillSimonds** [comment]
Hi all! I have this issue as well. I'm running a 2960X switch stack on 15.2(2)E7.

Regards,

**Comment by ktbyers** [comment]
Yes, this needs fixed in napalm. We can possibly put in a handler to catch this.

Although...I would say it is a Cisco bug/misdesign.

```
pynet-rtr1#configure replace flash:/candidate_config.txt ?
  force       Forcibly replace without prompting for user input
```

**Comment by jwbensley** [comment]
I'm having the same issue on CSR1000v - IOS-XE 03.16.07b.S.

Some routers have user1 on them, some have user2, some have both. I want to delete user1 and user2 from all routers so the merge config file looks like this:
```bash
bensley@LT-10383(NAPALM)$cat merge_config.txt

no username user1
no username user2

username user3 password user3
```

My python script does the following using the NAPALM library:
```python
device.open()
device.load_merge_candidate()
device.compare_config()
device.commit_config()
```

This is the output:
```bash
bensley@LT-10383(NAPALM)$./apply_config.py -i gns3_inventory.yml
Default password:
Trying R3...
Loaded merge config
R3:
-no username user1
-no username user2
+username user3 password user3
Merging config
Traceback (most recent call last):
  File "./apply_config.py", line 319, in <module>
    sys.exit(main())
  File "./apply_config.py", line 307, in main
    if not merge_config(dev, device):
  File "./apply_config.py", line 146, in merge_config
    device.commit_config()
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 453, in commit_config
    output = self._commit_hostname_handler(cmd)
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 385, in wrapper
    retval = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 410, in _commit_hostname_handler
    output = self.device.send_command_expect(cmd, expect_string=pattern)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1130, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 1112, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: [>##]\s*$
```

If I run the same commands NAPALM runs on the CLI interactively myself this is the output:
```bash
bensley@LT-10383(KeyMile)$ssh napalm@192.168.223.13
Password:

R3#show run | inc user
username napalm privilege 15 password 0 napalm
username user1 password 0 test
username user4 password 0 test

R3#more flash:merge_config.txt

no username user1
no username user2

username user3 password user3

R3#show archive config incremental-diffs flash:merge_config.txt ignorecase
!List of Commands:
no username user1
no username user2
username user3 password user3
end

R3#copy flash:merge_config.txt running-config
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]
```

This shows the confirm message which causes NAPALM to hang on waiting for the CLI prompt to appear. 

Is it possible rather than having NAPALM detect this specific block `[confirm]` to instead match a regex with something like `]$`, any setence that ends in a square bracket? Perhaps have a `optional_arg` that is `default=false` but when enabled matches `]$` and sends the ENTER keystroke? I think there are other commands that will require some sort of user interaction and place a message inside square brackets so that could be useful for other situations.

One example is the file prompts, for which Cisco do have a command to disable them, `file prompt quiet` but this would also cover that issue.

**Comment by jwbensley** [comment]
Forgot to provide the NAPALM CLI output as part of the FAQ:

```
$napalm --vendor ios --user napalm --password napalm 192.168.223.13 call get_facts
{
    "vendor": "Cisco",
    "model": "CSR1000V",
    "interface_list": [
        "GigabitEthernet1",
        "GigabitEthernet2",
        "GigabitEthernet3",
        "GigabitEthernet4"
    ],
    "fqdn": "R3.lab.net",
    "uptime": 5820,
    "hostname": "R3",
    "os_version": "CSR1000V Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 15.5(3)S7b, RELEASE SOFTWARE (fc1)",
    "serial_number": "9FRKD2WR7R7"
}
```

**Comment by ktbyers** [comment]
@jwbensley Can you see if this fix works:

https://github.com/napalm-automation/napalm/tree/confirm_username_fix

**Comment by jwbensley** [comment]
@ktbyers - Thanks I have tried this commit and now get a different error:
```
(napalm-text) bensley@LT-10383(NAPALM)$./apply_config.py -i gns3_inventory.yml
Default password:
Trying R3...
Loaded merge config
R3:
-no username user1
-no username usee2
+username user3 password user3
Merging config
Traceback (most recent call last):
 File "./apply_config.py", line 319, in <module>
   sys.exit(main())
 File "./apply_config.py", line 307, in main
   if not merge_config(dev, device):
 File "./apply_config.py", line 146, in merge_config
   device.commit_config()
 File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 466, in commit_config
   output = self._commit_handler(cmd)
 File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 385, in wrapper
   retval = f(self, *args, **kwargs)
 File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 425, in _commit_handler
   self.device.set_base_prompt()
 File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 915, in set_base_prompt
   raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: 'This operation will remove all username related configurations with same name.Do you want to continue? [confirm]'
```

I think that maybe the problem is that the regex search pattern isn't matching up to the end of the CLI output, I have added a square bracket to the end and it is now working for me:

```
pattern2 = r".*all username.*confirm]"
```

Before running my NAPALM script:
```
R3#show run | inc user
username napalm privilege 15 password 0 napalm
username user1 password 0 test
username user4 password 0 test
```

Script run:
```
(napalm-text) bensley@LT-10383(NAPALM)$./apply_config.py -i gns3_inventory.yml
Default password:
Trying R3...
Loaded merge config
R3:
-no username user1
-no username user2
+username user3 password user3
Merging config
Output: This operation will remove all username related configurations with same name.Do you want to continue? [confirm]
Done!
```

Router CLI output after script run:
```
username napalm privilege 15 password 0 napalm
username user3 password 0 user3
```

So it seems to fix it adding the closing square bracket. I assume the regex matches too early (albeit by two characters "]\n" and maybe sends the "y" character before the router is ready to take the input?).

**Comment by ktbyers** [comment]
@jwbensley Yeah...me cussing at Cisco (they shouldn't prompt at all...and they are prompting for each user).

I will have to update this and use a loop to handle all the confirms.

**Comment by ktbyers** [comment]
@jwbensley Okay, I have updated the PR to handle removing multiple usersnames:

https://github.com/napalm-automation/napalm/pull/829

Can you test it.

**Comment by jwbensley** [comment]
@ktbyers - Still not working:

```
ValueError: Router prompt not found: 'This operation will remove all username related configurations with same name.Do you want to continue? [confirm]'
```

However looking at the diff for the PR, there seems to be no change related to this bug, or as I not understanding the diff: https://github.com/napalm-automation/napalm/pull/829/files

```bash
(napalm) bensley@ubuntu-laptop:~/Python/napalm-test/napalm$ git branch
* confirm_username_fix

(napalm) bensley@ubuntu-laptop:~/Python/napalm-test/napalm$ git show
commit 07af933cbed26557df06ad471e3e953fc9cd0b85
Merge: ce375a3 8c66fe0
Author: Kirk Byers <ktbyers@twb-tech.com>
Date:   Sat Oct 13 09:35:20 2018 -0700
```

**Comment by jwbensley** [comment]
@ktbyers OK it's working now with a slight change...

Router output before running NAPALM script:
```
csr1000v-napalm(config)#do show run | inc user  
username napalm privilege 15 password 0 napalm
username user4 password 0 pass
username user1 password 0 pass
username user2 password 0 pass
```

merge_config.txt
```
no username user1
no username user2
username user3 password pass
```

Router output after NAPALM script run:
```
csr1000v-napalm(config)#do show run | inc user 
username napalm privilege 15 password 0 napalm
username user4 password 0 pass
username user3 password 0 pass
```

I just had to change from sending a "y" character to a new line character in the python:
```python
                new_output = self.device.send_command_timing(
                    "\n",
                    strip_prompt=False,
                    strip_command=False,
                )
```

I chucked some `print()` statements in and saw the following output with multiple `no username X` statements`:
```
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]y
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]

65 bytes copied in 0.167 secs (389 bytes/sec)
csr1000v-napalm#y
```

And I'd get the following error (I presume because of that `y` after the `#` on the prompt):
```
Traceback (most recent call last):
  File "./merge.py", line 110, in <module>
    sys.exit(main())
  File "./merge.py", line 101, in main
    device.commit_config()
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 476, in commit_config
    output = self._commit_handler(cmd)
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 385, in wrapper
    retval = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 435, in _commit_handler
    self.device.set_base_prompt()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 957, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 998, in find_prompt
    raise ValueError("Unable to find prompt: {}".format(prompt))
ValueError: Unable to find prompt: 
```

So changing to `\n` and it works fine :+1:

**Comment by jwbensley** [comment]
What I should have done is provided an actual diff, I forgot that there is another line changed, the regex search pattern and string were the wrong way around so it wasn't matching anything initially:

```bash
(napalm) bensley@ubuntu-laptop:~/Python/napalm-test/napalm$ git diff
diff --git a/napalm/ios/ios.py b/napalm/ios/ios.py
index 19e44c3..f23ea40 100644
--- a/napalm/ios/ios.py
+++ b/napalm/ios/ios.py
@@ -417,10 +417,10 @@ class IOSDriver(NetworkDriver):
         loop_count = 50
         new_output = output
         for i in range(loop_count):
-            if re.search(new_output, pattern2):
+            if re.search(pattern2, new_output):
                 # Send confirmation if username removal
                 new_output = self.device.send_command_timing(
-                    "y",
+                    "\n",
                     strip_prompt=False,
                     strip_command=False,
                 )
```

Without the regex fix I was getting the following error:
```
Traceback (most recent call last):
  File "./merge.py", line 110, in <module>
    sys.exit(main())
  File "./merge.py", line 101, in main
    device.commit_config()
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 472, in commit_config
    output = self._commit_handler(cmd)
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 385, in wrapper
    retval = f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/napalm/ios/ios.py", line 431, in _commit_handler
    self.device.set_base_prompt()
  File "/usr/local/lib/python3.5/dist-packages/netmiko/base_connection.py", line 959, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(repr(prompt)))
ValueError: Router prompt not found: 'This operation will remove all username related configurations with same name.Do you want to continue? [confirm]'
```

So two minor tweaks and the patch works.

**Comment by ktbyers** [comment]
@jwbensley Okay, updated PR to reflect this. Thanks for the testing.

**Comment by ktbyers** [comment]
Should be fixed.

**Comment by zakkymuhammad** [comment]
Hi, can you help me? I got this error when I was trying to test simple code with napalm. Thank you.

file 'candidate'
`hostname Router`

`from napalm import get_network_driver

driver = get_network_driver('ios')
others = {
			'secret':'cisco',
			'dest_file_system':'nvram:'
			}
device = driver(hostname='192.168.124.148', username='cisco', password='cisco', optional_args=others)
device.open()

device.load_merge_candidate(filename='candidate')
compare = device.compare_config()

print(compare)
device.commit_config()

device.close()`

`+hostname Router
Traceback (most recent call last):
  File "c.py", line 23, in <module>
    device.commit_config()
  File "/Users/zakky.muhammad/Downloads/tmp/Env/lib/python3.8/site-packages/napalm/ios/ios.py", line 555, in commit_config
    output += self.device.save_config()
  File "/Users/zakky.muhammad/Downloads/tmp/Env/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 37, in save_config
    return super(CiscoIosBase, self).save_config(
  File "/Users/zakky.muhammad/Downloads/tmp/Env/lib/python3.8/site-packages/netmiko/cisco_base_connection.py", line 224, in save_config
    output = self.send_command(command_string=cmd)
  File "/Users/zakky.muhammad/Downloads/tmp/Env/lib/python3.8/site-packages/netmiko/base_connection.py", line 1335, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command_expect: Router\#`
